name: neuronavi
description: A smart task management app for families with ADHD/Autism support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_app_check: ^0.2.1+18
  
  # State Management
  provider: ^6.1.1
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  
  # Functionality
  flutter_tts: ^3.8.5
  http: ^1.1.2
  uuid: ^4.2.2
  intl: ^0.18.1
  shared_preferences: ^2.2.2

  #AI
  google_generative_ai: ^0.2.2 
  
  # Utilities
  equatable: ^2.0.5
  # firebase_app_check: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
